sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: pp92k0KzvgZ/dOEHD+QC7bKeLnqURCYMrd2EVhBCO/OGfa7OHlJ/mFQ9PPjKFuUhuu/4u4FG+iGKCX7Hrpio+WRKBIWsJtB6eQioX7VGuJbMYax0AQ3lTvUky8MkTXA53GebsH5rSGOo+6clzBjx87VU/FAEzMD4RNRMiSg3AjCMRNM4AJPwgW6f7X0i7chSp7bqUKJ/N4TU99Nd07iYqA83BGDiDhJbCsvNkoARk/EU0wXozrpUiJbFMf6e2JSGEQ15vlA1TKlsDcTxgN7CqY7T1sfrwNwcqE4PbYw6PTCZ8lILs4sz7GkGRqV9jJF+PJviekKFGuOfxAcL2QUjJ3KCsToRRNxg1xXFiqlEc142rTGqU8fwUkjZv+xip7LhzQad0+BBexjwIqtuAjzsL2vFYRNDMLIHThs4DJy7orpNgsnXRamf/3Gt6fGFvWbcbrBX43Z9EPLuHHX0aSP/CEMfQlnBujsYiDRVC2VPh3L01XEF9rztMlGo8+mwTVjsyY+tmbhM9HYVrcBj0WKXSTPU50uHQYKLTdAwrB2Ni52XHYUUpMtT9nPR1DCONFgzSdt9XMw3LnK9Yn7Fls9Q4O48tXf3HNU8t+WP+9wkfo2rOI3MacbauH0743Fi3ikFHPVDpBen2C//3hau/PbaUb8WdclgAHlsnQpw3WRN0q8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Anthology-of-Massachusetts-Poets_2294
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy